-- App data stays outside Supabase's public Data API schema.
CREATE SCHEMA IF NOT EXISTS game;
CREATE TABLE IF NOT EXISTS game.users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS game.login_attempts (username TEXT PRIMARY KEY, failures INTEGER NOT NULL, last_attempt BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS game.players (id TEXT PRIMARY KEY, nickname TEXT NOT NULL, x DOUBLE PRECISION NOT NULL, z DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL, yaw DOUBLE PRECISION NOT NULL DEFAULT 0, jump DOUBLE PRECISION NOT NULL DEFAULT 0, running INTEGER NOT NULL DEFAULT 0, avatar TEXT NOT NULL DEFAULT '01m', user_id BIGINT REFERENCES game.users(id));
CREATE TABLE IF NOT EXISTS game.game_saves (user_id BIGINT PRIMARY KEY REFERENCES game.users(id), nickname TEXT NOT NULL, avatar TEXT NOT NULL, x DOUBLE PRECISION NOT NULL, z DOUBLE PRECISION NOT NULL, yaw DOUBLE PRECISION NOT NULL, pitch DOUBLE PRECISION NOT NULL DEFAULT 0, music_muted INTEGER NOT NULL DEFAULT 0, updated DOUBLE PRECISION NOT NULL, save_version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS game.messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nickname TEXT NOT NULL, body TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS players_updated_idx ON game.players(updated);
CREATE INDEX IF NOT EXISTS players_user_idx ON game.players(user_id);
ALTER TABLE game.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.game_saves ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON SCHEMA game FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA game FROM PUBLIC, anon, authenticated;

-- Additive pet migration preserves every existing account/save.
ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS dog_name TEXT NOT NULL DEFAULT '';

ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS dog_food INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS dog_xp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS food_claims TEXT NOT NULL DEFAULT '{}';
ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS dog_interaction_at DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS game.forum_posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES game.users(id),display_name TEXT NOT NULL,body TEXT NOT NULL,created DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS game.forum_images (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,post_id BIGINT NOT NULL REFERENCES game.forum_posts(id),jpeg_base64 TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS game.forum_comments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,post_id BIGINT NOT NULL REFERENCES game.forum_posts(id),user_id BIGINT NOT NULL REFERENCES game.users(id),display_name TEXT NOT NULL,body TEXT NOT NULL,created DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS forum_images_post_idx ON game.forum_images(post_id,id);
CREATE INDEX IF NOT EXISTS forum_comments_post_idx ON game.forum_comments(post_id,id);
CREATE INDEX IF NOT EXISTS forum_posts_user_idx ON game.forum_posts(user_id,id);
CREATE INDEX IF NOT EXISTS forum_comments_user_idx ON game.forum_comments(user_id,id);
ALTER TABLE game.forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.forum_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE game.forum_comments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON game.forum_posts, game.forum_images, game.forum_comments FROM PUBLIC, anon, authenticated;


-- Explicit backend-managed administrator role; registrations remain ordinary accounts.
ALTER TABLE game.users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game.forum_posts ADD COLUMN IF NOT EXISTS deleted_at DOUBLE PRECISION;
ALTER TABLE game.forum_posts ADD COLUMN IF NOT EXISTS deleted_by BIGINT REFERENCES game.users(id);
ALTER TABLE game.forum_comments ADD COLUMN IF NOT EXISTS deleted_at DOUBLE PRECISION;
ALTER TABLE game.forum_comments ADD COLUMN IF NOT EXISTS deleted_by BIGINT REFERENCES game.users(id);

ALTER TABLE game.game_saves ADD COLUMN IF NOT EXISTS animal_pets TEXT NOT NULL DEFAULT '{}';

CREATE TABLE IF NOT EXISTS game.world_objects (name TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0);
INSERT INTO game.world_objects(name,value) VALUES('room-door',0) ON CONFLICT(name) DO NOTHING;
ALTER TABLE game.world_objects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON game.world_objects FROM PUBLIC,anon,authenticated;

-- Account cosmetics are managed only by the backend, and survive deployments.
ALTER TABLE game.users ADD COLUMN IF NOT EXISTS avatar_frame TEXT NOT NULL DEFAULT '';

-- Associate temporary speech bubbles with the actual sending player.
ALTER TABLE game.messages ADD COLUMN IF NOT EXISTS player_id TEXT NOT NULL DEFAULT '';
