import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from '../static/vendor/three.module.js';import {GLTFLoader} from '../static/vendor/GLTFLoader.js';import {createHubScene,hubStep} from '../static/earth-hub.js';
globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:1,height:1});globalThis.ProgressEvent=class{};
GLTFLoader.prototype.loadAsync=function(url){const b=fs.readFileSync('static/models/'+url.split('/').at(-1));return this.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');};
const scene=new THREE.Scene(),hub=await createHubScene(scene);assert.equal(scene.background.getHex(),0);assert.equal(hub.folders.length,3);assert.equal(hub.folders[0].userData.destination,'town');assert(hub.folders.slice(1).every(f=>f.userData.destination===null));
for(const folder of hub.folders){assert(Math.abs(Math.hypot(folder.position.x,folder.position.z)-5)<.001);assert.equal(folder.position.y,hub.earth.position.y);}
const initial=hub.folders[0].position.clone();hub.update(12);assert(hub.earth.rotation.y>0);assert(hub.folders[0].position.distanceTo(initial)>1);hub.update(0);assert(hub.folders[0].position.distanceTo(initial)<.001);
const player=new THREE.Vector3(0,1.65,12);assert(hubStep(player,0,1,0,1));assert.equal(player.z,8.5);assert.equal(player.y,1.65);assert(hubStep(player,0,0,1,1));assert.equal(player.x,3.5);
player.set(0,1.65,2.3);assert(!hubStep(player,0,1,0,.1));assert.equal(player.z,2.3);player.set(0,1.65,23.9);assert(!hubStep(player,0,-1,0,.1));
const html=fs.readFileSync('templates/index.html','utf8');assert(html.includes('Town Life'));assert(!html.includes('earthModel'));assert(!html.includes('click earth to enter'));assert(html.includes('earthHub?.stop()'));assert(html.includes('earthMusic.pause()'));assert(html.includes("onTown:()=>{closeEarth();location.href='/world';}"));console.log('Actual earth/folder GLBs load; eye-level geometry, slow spin, orbit and reset, walking boundaries, Town Life route and exit cleanup passed.');
